version: '3.8'

services:
  krakend:
    image: devopsfaith/krakend:2.9.1
    container_name: krakend-api-gateway
    ports:
      - "8003:8080" 
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json:ro 
    environment:
      - KRAKEND_PORT=8080
    networks:
          - lab

networks:
  lab: