version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:${MINIO_VERSION}
    restart: always
    command: server --console-address ":9001"  /data
    ports:
      - ${PORT_MINIO}:9000
      - ${PORT_MINIO_CONSOLE}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER=${MINIO_BROWSER}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12222/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      - lab

volumes:
  minio-data:

networks:
  lab:
